## Question 0
- Please download the datasets from the following link,  https://www.kaggle.com/aaron7sun/stocknews
- Save the download files on your drive and load the file.

In [0]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import pandas as pd
corpus_root = 'drive/My Drive/Colab Notebooks/datasets/'

In [0]:
news_df = pd.read_csv(corpus_root+'RedditNews.csv')
stock_df = pd.read_csv(corpus_root+'upload_DJIA_table.csv')

In [0]:
news_df.head()

         Date                                               News
0  2016-07-01  A 117-year-old woman in Mexico City finally re...
1  2016-07-01   IMF chief backs Athens as permanent Olympic host
2  2016-07-01  The president of France says if Brexit won, so...
3  2016-07-01  British Man Who Must Give Police 24 Hours' Not...
4  2016-07-01  100+ Nobel laureates urge Greenpeace to stop o...

In [0]:
stock_df.head(15)

          Date          Open  ...     Volume     Adj Close
0   2016-07-01  17924.240234  ...   82160000  17949.369141
1   2016-06-30  17712.759766  ...  133030000  17929.990234
2   2016-06-29  17456.019531  ...  106380000  17694.679688
3   2016-06-28  17190.509766  ...  112190000  17409.720703
4   2016-06-27  17355.210938  ...  138740000  17140.240234
5   2016-06-24  17946.630859  ...  239000000  17400.750000
6   2016-06-23  17844.109375  ...   98070000  18011.070312
7   2016-06-22  17832.669922  ...   89440000  17780.830078
8   2016-06-21  17827.330078  ...   85130000  17829.730469
9   2016-06-20  17736.869141  ...   99380000  17804.869141
10  2016-06-17  17733.439453  ...  248680000  17675.160156
11  2016-06-16  17602.230469  ...   91950000  17733.099609
12  2016-06-15  17703.650391  ...   94130000  17640.169922
13  2016-06-14  17710.769531  ...   93740000  17674.820312
14  2016-06-13  17830.500000  ...  101690000  17732.480469

[15 rows x 7 columns]

## Question 1
- There are two channels of data provided in this dataset:

  - **News data:** Crawled historical news headlines from Reddit WorldNews Channel . They are ranked by reddit users' votes, and only the top 25 headlines are considered for a single date. (Range: 2008-06-08 to 2016-07-01)

  - **Stock data:** Dow Jones Industrial Average (DJIA) is used to "prove the concept". (Range: 2008-08-08 to 2016-07-01)

- Define a *funtion* aims to know the weekly (7 days) Stock **Close value** trend. For example, 
  - Case 1 & 2, if a close value is more than the value which is 7 days later, will be regard as **decreased (0)**. In the other hands, if a close value less than the 7 days later value, should be **increase (1)**.
    
  - Case 3, if we don't have 7 days later data, please label the day as **-1**.

- Map your label on news data.

In [0]:
import datetime
def label():
  '''
  please answer here, you can add any parameters if you want.
  but don't import other libraries, this notebook already prepared the libraries which all you need !
  remember that, the standard for evaluation include your:
    1. Time Complexity (80%)
    2. Program Logic (10%)
    3. Creativity (10%)
  '''

In [0]:
'''
than apply your defined function on stock_df here.
return results store into a new columns name "Label"

'''

'\nthan apply your defined function on stock_df here.\nreturn results store into a new columns name "Label"\n\n'

In [0]:
def news_label():
  '''
  Map your close value trend label in news data by date, also name it "Label"
  if a date does not appear in the stock data, also label it as -1.
  e.g. all news in 2016-06-30 will be label -1
  '''
  return

## Question 2: Test Time Augmentation implementation
- Test-time augmentation, or TTA for short, is an application of data augmentation to the test dataset. Specifically, it involves creating multiple augmented copies of each image in the test set, having the model make a prediction for each, then returning an ensemble of those predictions. 
 [- refference from.](https://machinelearningmastery.com/how-to-use-test-time-augmentation-to-improve-model-performance-for-image-classification/)
- **Introduce this technique as far as you can.** (30%)
- After training stage, you receive two list on testing stage.
  1. org_sentences: a **list** of string, also are sentence which will be predict by trained model.
  2. aug_setnecnes: a **list** of dict, are sentences which augmented by orginal sentences, each augmented sentence will give a corresponding predicted result. *One* original sentence will augment *five* sentence.

  4. Return **list of dict** to save the original sentence and it's corresponding answer.

- Define a function find the most frequence answer, and regard it as orginal sentence's result. (70%)
  - e.g. org_sentences: ['I love you']
  - aug_sentences: [{'I like you':1, 'I very love you':1, 'I relly love you':1, 'I hate you':0, 'I don't like you':0}]
  - **return**: [{'I love you':1}]
- Tips: In this case only have two label: **1 or 0**, show your ability to process the specify question.

In [0]:
'''
Defined input
'''
org_sentences = ['manager embarrassed himself .','hannah was very friendly and courteous .','i went to this location and was going to pay asap .','no , i replied .','the staff is awesome and the place is always clean .']
aug_sentences = [{'manager said , that was a mistake .':1,'his staff is embarrassed .':0,'even tho it was the employees mistake .':1,'shame on that manager .':0,'the manager was rude .':0},
                 {'amanda was courteous and very friendly !':1,'in addition , she was courteous and very nice .':1,'she was very pleasant , friendly , and efficient .':1,'nancy was very friendly and courteous , and did a great job .':0,'everyone was friendly and made you feel welcome .':0},
                 {'when i walked in they had me pay right away .':0,'i will definitely be back here -- next paycheck !':0,'once i was going to pay they said it is _num_ for both !':1,'i bought this and i had to return it right away .':0,'i made an order today and attempted to pay with exact change .':0},
                 {'they responded no .':0,'i said , no thanks .':0,'they reply no .':0,'me : `` no .':0,'um , no thanks .':1},
                 {'it is always clean and the staff is awesome .':1,'the employees are super nice and the place is always clean .':1,'the place is always clean and their work is consistently great .':1,'employees are always nice , always fresh and tasty as usual .':0,'i am happy with their service and friendly technicians .':0}]

In [0]:
def TTA_processing(org_sentences, aug_sentences):
  answer = []

  return answer

# Question 3: Compute cosine similarity on TF-IDF (term frequency–inverse document frequency)
-  **Cosine similarity** is a measure of similarity between two non-zero vectors of an inner product space that measures the cosine of the angle between them. 
- **TF-IDF** is a numerical statistic that is intended to reflect how important a word is to a document in a collection or corpus

1. Please answer why we can use cosine similarity to measure TF-IDF representation, has any other representation methods also can be measured by cosine similarity. (20%)
2. Define a converting function compute tf-idf vector from a list of ducoments. (40%)
3. Define a scoring function to compute the cosine similarity between two input vector. (30%)
4. Show the cross comparation table for the given sentences. (10%)

In [0]:
documents = ['terrible service this time','terrible terrible service','most terrible service','terrible service and experience','what a terrible service','so terrible service experience','what a terrible disappointment','what a terrible place','this time it was so horrible','the staff was horrible']

In [0]:
'''
Answer here
you can define other functions to support the defined function if you need.

TF-IDF dataframe show as the following table.
'''
import numpy as np
import math
def computTFIDF(documents):

  return

In [0]:
df = pd.DataFrame(computTFIDF(documents))
df

       this  terrible   service  staff  ...      time        a        it   and
0  0.174743  0.024228  0.055462   0.00  ...  0.174743  0.00000  0.000000  0.00
1  0.000000  0.064607  0.073950   0.00  ...  0.000000  0.00000  0.000000  0.00
2  0.000000  0.032303  0.073950   0.00  ...  0.000000  0.00000  0.000000  0.00
3  0.000000  0.024228  0.055462   0.00  ...  0.000000  0.00000  0.000000  0.25
4  0.000000  0.024228  0.055462   0.00  ...  0.000000  0.13072  0.000000  0.00
5  0.000000  0.024228  0.055462   0.00  ...  0.000000  0.00000  0.000000  0.00
6  0.000000  0.024228  0.000000   0.00  ...  0.000000  0.13072  0.000000  0.00
7  0.000000  0.024228  0.000000   0.00  ...  0.000000  0.13072  0.000000  0.00
8  0.116495  0.000000  0.000000   0.00  ...  0.116495  0.00000  0.166667  0.00
9  0.000000  0.000000  0.000000   0.25  ...  0.000000  0.00000  0.000000  0.00

[10 rows x 17 columns]

In [0]:
'''
Answer here
return the cosine similarity between the given two vectors
Apply the function which you designed to all sentences, and show your scoring results as the following table.
'''
def cosine_sim(vec_a, vec_b):

  return score

          0         1         2  ...         7         8         9
0  1.000000  0.226813  0.055972  ...  0.007397  0.517451  0.000000
1  0.226813  1.000000  0.224349  ...  0.051111  0.000000  0.000000
2  0.055972  0.224349  1.000000  ...  0.007317  0.000000  0.000000
3  0.046299  0.185576  0.045796  ...  0.006053  0.000000  0.000000
4  0.074014  0.296664  0.073209  ...  0.573020  0.000000  0.000000
5  0.056587  0.226813  0.055972  ...  0.007397  0.258725  0.000000
6  0.007397  0.051111  0.007317  ...  0.357407  0.000000  0.000000
7  0.007397  0.051111  0.007317  ...  1.000000  0.000000  0.000000
8  0.517451  0.000000  0.000000  ...  0.000000  1.000000  0.305206
9  0.000000  0.000000  0.000000  ...  0.000000  0.305206  1.000000

[10 rows x 10 columns]